<?php

namespace Src\controllers;

class AdminController extends BaseController
{
    public function create()
    {

    }
    public function delete()
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }
    public function edit($id)
    {
        parent::edit($id); // TODO: Change the autogenerated stub
    }
    public function read()
    {
        parent::read(); // TODO: Change the autogenerated stub
    }
    public function store()
    {
        parent::store(); // TODO: Change the autogenerated stub
    }
    public function update()
    {
        parent::update(); // TODO: Change the autogenerated stub
    }
    public function confirm(){


    }


}