<?php

namespace Src\controllers;

class HomeController extends BaseController
{

    public function create()
    {
        parent::create(); // TODO: Change the autogenerated stub
    }
    public function delete()
    {

        parent::delete(); // TODO: Change the autogenerated stub
    }
    public function edit($id)
    {
        parent::edit($id); // TODO: Change the autogenerated stub
    }
    public function read()
    {
        parent::read(); // TODO: Change the autogenerated stub
    }
    public function store()
    {
        parent::store(); // TODO: Change the autogenerated stub
    }
    public function update()
    {
        parent::update(); // TODO: Change the autogenerated stub
    }
    public function index(){

        view('Home/index');
    }

}