<?php

namespace Src\controllers;

class LoginController extends BaseController
{

    public function create()
    {
        parent::create(); // TODO: Change the autogenerated stub
    }
    public function delete()
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }
    public function edit($id)
    {
        parent::edit($id); // TODO: Change the autogenerated stub
    }
    public function read()
    {
        parent::read(); // TODO: Change the autogenerated stub
    }
    public function store()
    {

    view('Login/create');
    }
    public function update()
    {
        parent::update(); // TODO: Change the autogenerated stub
    }

}