<?php

namespace Src\controllers;

class RegisterController extends BaseController
{
    public function create()
    {


    }
    public function delete()
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }
    public function edit($id)
    {
        parent::edit($id); // TODO: Change the autogenerated stub
    }
    public function read()
    {
        parent::read(); // TODO: Change the autogenerated stub
    }
    public function store()
    {
        $user =[
          'name' => $_POST['first_name']  ,
            'last name '=>$_POST['last_name'],
            'email' => $_POST['email'],
            'type'=> $_POST['type'],
            'password'=> $_POST['password']
        ];

    }
    public function update()
    {
        parent::update(); // TODO: Change the autogenerated stub
    }

}